/*
 * Copyright 2025, University of Turin
 * Copyright 2016-2024, Intel Corporation
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in
 *       the documentation and/or other materials provided with the
 *       distribution.
 *
 *     * Neither the name of the copyright holder nor the names of its
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * patcher.c -- patching a library
 *
 * Jumping from the subject library:
 *
 *     /--------------------------\
 *     |               subject.so |
 *     |                          |
 *     |  jr to_trampoline_table  |  patched by activate_patches()
 *  /->|   |                      |
 *  |  \___|______________________/
 *  |      |
 *  |  /---|--------------------------\
 *  |  | load wrapper_address into t6 | jr generated by activate_patches()
 *  |  | jr t6                        | This allows subject.so and
 *  |  |   |                          | libsyscall_intercept.so to be farther
 *  |  \___|__________________________/ than 2 gigabytes from each other
 *  |      |
 *  |  /---|-----------------------------\
 *  |  |   |  libsyscall_intercept.so    |
 *  |  |   |                             |
 *  |  | /-|--------------------------\  |
 *  |  | | |  static unsigned char    |  |
 *  |  | | |  asm_wrapper_space[]     |  |
 *  |  | | |    in BSS                |  | wrapper routine
 *  |  | | |                          |  | generated into asm_wrapper_space
 *  |  | | |                          |  | by create_wrapper()
 *  |  | |wrapper routine             |  |
 *  |  | |calls C hook function  ----------> intercept_routine in intercept.c
 *  |  | |load return address into t6 |  |
 *  |  | |jr t6                       |  |
 *  |  | \_|__________________________/  |
 *  |  \___|_____________________________/
 *  |      |
 *  \______/
 *
 */

#include <intercept.h>
#include <intercept_util.h>
#include <intercept_log.h>

#include <assert.h>
#include <stdint.h>
#include <syscall.h>
#include <sys/mman.h>
#include <string.h>

#include <stdio.h>
#include <sys/auxv.h>

#define COMPAT_HWCAP_ISA_C (1 << ('C' - 'A'))
#define COMPAT_HWCAP_ISA_V (1 << ('V' - 'A'))

/* The size of a trampoline jump, see src/arch/riscv/asm_wrapper.md */
enum { TRAMPOLINE_SIZE = 4 * 23 };

static void create_wrapper(struct patch_desc *patch, unsigned char **dst);
static void create_load_uint64t_into_t0(uint8_t *code, uint64_t value);
static void create_load_uint64t_into_t6(uint8_t *code, uint64_t value);

/*
 * create_absolute_jump(from, to)
 * Writes the machine code of a trampoline at from jumping to to; 92 bytes are
 * needed to make sure to correctly encoding a 64-bit constant into t6,
 * whihch we assume being clobbered in the version 1.0 of the RISC-V porting.
 * Auxiliary temporary registers must be saved and restored so that they are
 * not clobbered as well. The conformation of the trampoline requires
 * 4 bytes * 23 instructions.
 */
static unsigned char *
create_absolute_jump(unsigned char *from, void *to)
{
	uint32_t *instructions = (uint32_t *)from;
	instructions[0] = 0xfe010113; // addi sp, sp, -32
	instructions[1] = 0x00613023; // sd t1, 0(sp)
	instructions[2] = 0x00713423; // sd t2, 8(sp)
	instructions[3] = 0x01c13823; // sd t3, 16(sp)
	instructions[9] = 0x7ffff337; // lui t1, 0x7ffff
	instructions[10] = 0x7ff06393; // ori t2, zero, 0x7ff
	instructions[11] = 0x00139393; // slli t2, t2, 1
	instructions[12] = 0x0013e393; // ori t2, t2, 1
	instructions[13] = 0x00736333; // or t1, t1, t2
	instructions[14] = 0x00131313; // slli t1, t1, 1
	instructions[15] = 0x00136313; // ori t1, t1, 1
	instructions[16] = 0x006e7e33; // and t3, t3, t1
	instructions[17] = 0x01cfefb3; // or t6, t6, t3
	instructions[18] = 0x00013303; // ld t1, 0(sp)
	instructions[19] = 0x00813383; // ld t2, 8(sp)
	instructions[20] = 0x01013e03; // ld t3, 16(sp)
	instructions[21] = 0x02010113; // addi sp, sp, 32
	instructions[22] = 0x000f8067; // jalr zero, t6, 0
    	// next call writes five 4-byte instructions starting from instructions[4]
	create_load_uint64t_into_t6((uint8_t *)(instructions + 4),(uint64_t)to);
	return (unsigned char *)(instructions + 23);
}

/*
 * check_trampoline_usage -
 * Make sure the trampoline table allocated at the beginning of patching has
 * enough space for all trampolines. This just aborts the process if the
 * allocate space does not seem to be enough, but it can be fairly easy
 * to implement more allocation here if such need would arise.
 */
static void
check_trampoline_usage(const struct intercept_desc *desc)
{
	if (!desc->uses_trampoline_table)
		return;

	/*
	 * We might actually not have enough space for creating
	 * more trampolines.
	 */

	size_t used = (size_t)(desc->next_trampoline - desc->trampoline_table);

	if (used + TRAMPOLINE_SIZE >= desc->trampoline_table_size)
		xabort("trampoline space not enough");
}

/*
 * is_copiable_before_syscall
 * checks if an instruction found before a syscall instruction
 * can be copied (and thus overwritten).
 */
static bool
is_copiable_before_syscall(struct intercept_disasm_result ins)
{
	if (!ins.is_set)
		return false;

	return !(ins.has_ip_relative_opr ||
	    ins.is_jump ||
	    ins.is_syscall ||
	    ins.uses_t6);
}

/*
 * is_copiable_after_syscall
 * checks if an instruction found after a syscall instruction
 * can be copied (and thus overwritten).
 *
 * Notice: we allow the copy of ret instructions.
 */
static bool
is_copiable_after_syscall(struct intercept_disasm_result ins)
{
	if (!ins.is_set)
		return false;

	return !(ins.has_ip_relative_opr ||
	    ins.is_jump ||
	    ins.is_syscall ||
	    ins.uses_t6);
}


/*
 * check_surrounding_instructions
 * Sets up the following members in a patch_desc, based on
 * instruction being relocatable or not:
 * uses_prev_ins ; uses_prev_ins_2 ; uses_next_ins
 */
static void
check_surrounding_instructions(struct intercept_desc *desc,
				struct patch_desc *patch)
{
	patch->uses_prev_ins = (is_copiable_before_syscall(patch->preceding_ins) &&
	    !has_jump(desc, patch->syscall_addr));

	if (patch->uses_prev_ins) {
		patch->uses_prev_ins_2 = (patch->uses_prev_ins &&
		    is_copiable_before_syscall(patch->preceding_ins_2) &&
		    !has_jump(desc, patch->syscall_addr - patch->preceding_ins.length));
	} else {
		patch->uses_prev_ins_2 = false;
	}

	patch->uses_next_ins = (is_copiable_after_syscall(patch->following_ins) &&
	    !has_jump(desc, patch->syscall_addr + SYSCALL_INS_SIZE));
}

/*
 * create_patch_wrappers - create the custom assembly wrappers
 * around each syscall to be intercepted. Well, actually, the
 * function create_wrapper does that, so perhaps this function
 * deserves a better name.
 * What this function actually does, is figure out how to create
 * a jump instruction in libc ( which bytes to overwrite ).
 * If it successfully finds suitable bytes for hotpatching,
 * then it determines the exact bytes to overwrite, and the exact
 * address for jumping back to libc.
 *
 * This is all based on the information collected by the routine
 * find_syscalls, which does the disassembling, finding jump destinations,
 * finding padding bytes, etc...
 */
void
create_patch_wrappers(struct intercept_desc *desc, unsigned char **dst)
{
	unsigned short min_treshold = JUMP_INS_SIZE;
	bool c_isa_supported = getauxval(AT_HWCAP) & COMPAT_HWCAP_ISA_C;
	for (unsigned patch_i = 0; patch_i < desc->count; ++patch_i) {
		struct patch_desc *patch = desc->items + patch_i;
		debug_dump("patching %s:0x%lx - patch_number: %u\n", desc->path,
				patch->syscall_addr - desc->base_addr, patch_i);

			/*
			 * Check the instructions surrounding the syscall instruction.
			 * If they can be relocated, then they can be overwritten.
			 * Of course some instructions depend on the value of the
             		 * PC register, these can not be relocated.
			 */

			check_surrounding_instructions(desc, patch);

			/*
			 * Count the number of overwritable bytes
			 * in the variable length.
			 * Sum up the bytes that can be overwritten.
			 * The 4 bytes of the ecall instruction can
			 * be overwritten definitely, so length starts
			 * as SYSCALL_INS_SIZE ( 4 bytes ).
			 */
			unsigned short length = SYSCALL_INS_SIZE;

			patch->needs_compressed_ins = false;
			patch->padding_is_needed = false;
			patch->dst_jmp_patch = patch->syscall_addr;

			/*
			 * If the preceding instruction is relocatable,
			 * add its length. Also, the instruction right
			 * before that.
			 */
			if (patch->uses_prev_ins) {
				length += patch->preceding_ins.length;
				patch->dst_jmp_patch -=
				    patch->preceding_ins.length;

				if (patch->uses_prev_ins_2 && (length < JUMP_INS_SIZE)) {
					length += patch->preceding_ins_2.length;
					patch->dst_jmp_patch -=
					    patch->preceding_ins_2.length;
				} else {
					/*
					 * If it could be used but is not necessary we need
					 * to set the flag to false so that it's not relocated
					 */
					patch->uses_prev_ins_2 = false;
				}
			}

			/*
			 * If the following instruction is relocatable,
			 * add its length. This also affects the return address.
			 * Normally, the library would return to libc after
			 * handling the syscall by jumping to instruction
			 * right after the syscall. But if that instruction
			 * is overwritten, the returning jump must jump to
			 * the instruction after it.
			 */
			if (patch->uses_next_ins && (length < JUMP_INS_SIZE)) {
				length += patch->following_ins.length;

				/*
				 * Address of the ecall instruction
				 * plus 4 bytes
				 * plus the length of the following instruction
				 *
				 * adds up to:
				 *
				 * the address of the second instruction after
				 * the syscall.
				 */
				patch->return_address = patch->syscall_addr +
				    SYSCALL_INS_SIZE +
				    patch->following_ins.length;
			} else {
				/*
				 * If it could be used but is not necessary we need
				 * to set the flag to false so that it's not relocated
				 */
				patch->uses_next_ins = false;
				patch->return_address = patch->syscall_addr +  SYSCALL_INS_SIZE;
			}

			/* The following happens when we found 6 suitable bytes for
			 * rewriting and a 4-byte instruction is found after those,
			 * resulting in patch size being 10 bytes but just 8 are used so
			 * padding with a c.ebreak will be reasonable
			 */
			if (length > JUMP_INS_SIZE) {
				patch->padding_is_needed = true;
			}

			/*
			 * Check if compressed instructions module is supported by the CPU.
			 * If yes, 6 bytes are enough to place an auipc+c.jalr sequence.
			 * If the length of the patch is exactly 6 bytes, then we assert
			 * the flag marking the need of said sequence.
			 *
			 * If length is less than minimum needed bytes (value depending on
			 * ISA C module being supported or not), give up.
			 */
			if (c_isa_supported) {
				if (length == 6) {
					patch->needs_compressed_ins = true;
				}
				min_treshold = 6;
			}
			if (length < min_treshold) {
				char buffer[0x1000];

				int l = snprintf(buffer, sizeof(buffer),
					"unintercepted ecall at: %s 0x%lx\n",
					desc->path,
					patch->syscall_offset);

				intercept_log(buffer, (size_t)l);
				debug_dump("unintercepted ecall at: %s 0x%lx\n",
					desc->path,
					patch->syscall_offset);
				xabort("not enough space for patching"
				    " around ecall");
			}

		mark_jump(desc, patch->return_address);

		create_wrapper(patch, dst);
	}
}

/*
 * Referencing symbols defined in intercept_template.s
 */
extern unsigned char intercept_asm_wrapper_tmpl[];
extern unsigned char intercept_asm_wrapper_tmpl_end;
extern unsigned char intercept_asm_wrapper_patch_desc_addr;
extern unsigned char intercept_asm_wrapper_wrapper_level1_addr;
extern unsigned char intercept_wrapper;

size_t asm_wrapper_tmpl_size;
static ptrdiff_t o_patch_desc_addr;
static ptrdiff_t o_wrapper_level1_addr;

bool is_v_extension_supported;

/*
 * init_patcher
 * Some variables need to be initialized before patching.
 * This routine must be called once before patching any library.
 */
void
init_patcher(void)
{
	unsigned char *begin = &intercept_asm_wrapper_tmpl[0];

	assert(&intercept_asm_wrapper_tmpl_end > begin);
	assert(&intercept_asm_wrapper_patch_desc_addr > begin);
	assert(&intercept_asm_wrapper_wrapper_level1_addr > begin);
	assert(&intercept_asm_wrapper_patch_desc_addr <
		&intercept_asm_wrapper_tmpl_end);
	assert(&intercept_asm_wrapper_wrapper_level1_addr <
		&intercept_asm_wrapper_tmpl_end);

	asm_wrapper_tmpl_size =
		(size_t)(&intercept_asm_wrapper_tmpl_end - begin);
	o_patch_desc_addr = &intercept_asm_wrapper_patch_desc_addr - begin;
	o_wrapper_level1_addr =
		&intercept_asm_wrapper_wrapper_level1_addr - begin;

    is_v_extension_supported = getauxval(AT_HWCAP) & COMPAT_HWCAP_ISA_V;
}

/*
 * create_load_uint64t_into_tn
 * Generates the first 5 instructions (LUI,ADDI,SLLI,LUI,ADDI) of a
 * 14 instructions sequence that loads a 64 bit constant into a register.
 * See intercept_template.S for the following 9 at
 * intercept_asm_wrapper_patch_desc_addr (an equal sequence is placed at
 * intercept_asm_wrapper_wrapper_level1_addr as well).
 */
static void
create_load_uint64t_into_t0(uint8_t *code, uint64_t value)
{

	uint32_t *instructions = (uint32_t *)code;
	uint32_t upper_32 = (value & 0xffffffff00000000) >> 32;
	uint32_t lower_32 = (uint32_t)value;

	uint32_t lui_imm_field = upper_32 & 0xfffff000;
  uint32_t addi_imm_field = 0;
  if (upper_32 % 4096 != 0) {
    addi_imm_field = upper_32 - lui_imm_field;
    if (addi_imm_field > 2047) {
      lui_imm_field += 4096;
      addi_imm_field = -(4096 - addi_imm_field);
    }
  }

	instructions[0] = 0x000002b7 | lui_imm_field; // lui t0, 0x.....
  instructions[1] = 0x00028293 | (addi_imm_field << 20); // addi t0, t0, 0x...
  instructions[2] = 0x02029293; // slli t0, t0, 32

	lui_imm_field = lower_32 & 0xfffff000;
	addi_imm_field = 0;
	if (lower_32 % 4096 != 0) {
		addi_imm_field = lower_32 - lui_imm_field;
		if (addi_imm_field > 2047) {
			lui_imm_field += 4096;
			addi_imm_field = -(4096 - addi_imm_field);
		}
	}

	instructions[3] = 0x00000e37 | lui_imm_field; // lui t3, 0x.....
  instructions[4] = 0x000e0e13 | (addi_imm_field << 20); // addi t3, t3, 0x...
}

static void
create_load_uint64t_into_t6(uint8_t *code, uint64_t value)
{

	uint32_t *instructions = (uint32_t *)code;
	uint32_t upper_32 = (value & 0xffffffff00000000) >> 32;
	uint32_t lower_32 = (uint32_t)value;

	uint32_t lui_imm_field = upper_32 & 0xfffff000;
	uint32_t addi_imm_field = 0;
	if (upper_32 % 4096 != 0) {
		addi_imm_field = upper_32 - lui_imm_field;
		if (addi_imm_field > 2047) {
			lui_imm_field += 4096;
			addi_imm_field = -(4096 - addi_imm_field);
		}
	}

	instructions[0] = 0x00000fb7 | lui_imm_field; // lui t6, 0x.....
	instructions[1] = 0x000f8f93 | (addi_imm_field << 20); // addi t6, t6, 0x...
	instructions[2] = 0x020f9f93; // slli t6, t6, 32

	lui_imm_field = lower_32 & 0xfffff000;
	addi_imm_field = 0;
	if (lower_32 % 4096 != 0) {
		addi_imm_field = lower_32 - lui_imm_field;
		if (addi_imm_field > 2047) {
			lui_imm_field += 4096;
			addi_imm_field = -(4096 - addi_imm_field);
		}
	}

	instructions[3] = 0x00000e37 | lui_imm_field; // lui t3, 0x.....
	instructions[4] = 0x000e0e13 | (addi_imm_field << 20); // addi t3, t3, 0x...
}

/*
 * relocate_instruction
 * Places an instruction equivalent to `ins` to the memory location at `dst`.
 * Only handles instructions that can be copied verbatim, and some LEA
 * instructions.
 */
static unsigned char *
relocate_instruction(unsigned char *dst,
			const struct intercept_disasm_result *ins)
{
		memcpy(dst, ins->address, ins->length);
		return dst + ins->length;
}

/*
 * create_wrapper
 * Generates an assembly wrapper. Copies the template written in
 * intercept_template.s, and generates the instructions specific
 * to a particular ecall into the new copy.
 * After this wrapper is created, a ecall can be replaced with a
 * jump to this wrapper, and wrapper is going to call dest_routine
 * (actually only after a call to mprotect_asm_wrappers).
 */
static void
create_wrapper(struct patch_desc *patch, unsigned char **dst)
{
	/* Create a new copy of the template */
	patch->asm_wrapper = *dst;

	/* Copy the previous instruction(s) */
	if (patch->uses_prev_ins) {
		if (patch->uses_prev_ins_2) {
			*dst = relocate_instruction(*dst, &patch->preceding_ins_2);
		}
		*dst = relocate_instruction(*dst, &patch->preceding_ins);
	}

	memcpy(*dst, intercept_asm_wrapper_tmpl, asm_wrapper_tmpl_size);
	create_load_uint64t_into_t0(*dst + o_patch_desc_addr, (uintptr_t)patch);
	create_load_uint64t_into_t0(*dst + o_wrapper_level1_addr,
				(uintptr_t)&intercept_wrapper);
	*dst += asm_wrapper_tmpl_size;

	/* Copy the following instruction */
	if (patch->uses_next_ins)
		*dst = relocate_instruction(*dst, &patch->following_ins);

	*dst = create_absolute_jump(*dst, patch->return_address);
}

/*
 * create_j(from, to)
 * Create an 8 byte instructions sequence (LUI + JALR) which allows
 * to reach trampoline if its displacement is within -2 GiB or JALR_MAX_OFFSET,
 * which is (+2 GiB - 2050 Bytes).
 */
void
create_j(unsigned char *from, void *to)
{
	/*
	 * The operand is the difference between the
	 * instruction pointer pointing to the instruction
	 * just after the call, and the to address.
	 */
	ptrdiff_t delta = ((unsigned char *)to) - from;
	uint32_t *instructions = (uint32_t *)from;
	debug_dump("%p: ecall -> jalr %ld\t# %p\n", from, delta, to);

	const ptrdiff_t JALR_MAX_OFFSET =  ABS_MAX_POS_OFFSET; // ((2^31-1)-4095)+(2^11-2) = 0x7ffff000 + 0x7fe
	const ptrdiff_t JALR_MIN_OFFSET = -(ABS_MAX_NEG_OFFSET); // (-2^31) = -0x80000000 - 0x800

	if ((delta & 0x1) != 0) {

		xabort("create_j misaligned instruction fetch exception");

	}
	if (delta <= JALR_MAX_OFFSET && delta >= JALR_MIN_OFFSET) {

		uint32_t auipc = 0x00000f97; // auipc t6, 0x.....
		uint32_t jalr = 0x000f8067; // jalr zero, t6, 0x...
		uint32_t jalr_imm_field = 0;
		uint32_t auipc_imm_field = (uint32_t)delta & 0xfffff000; // offset[31:12]

		/*
		 * if the offset is not a multiple of 4096 the 12 least significant bits
		 * of its value must be set by adding the correct immediate value contained
		 * in jalr imm field to the rs1 value which is set by auipc instruction
		 * preceding jalr
		 */
		if ((uint32_t)delta % 4096 != 0) {
			jalr_imm_field = (uint32_t)delta - auipc_imm_field;
			if (jalr_imm_field > 2046) {
				auipc_imm_field += 4096;
				jalr_imm_field = -(4096 - jalr_imm_field);
			}
		}
	    auipc |= auipc_imm_field;
	    jalr |= (jalr_imm_field << 20);
		instructions[0] = auipc; // auipc t6, 0x.....
		instructions[1] = jalr; // jalr zero, t6, 0x...
	} else {
		xabort("create_j distance check");
	}
}

void
create_c_j(unsigned char *from, void *to) {
	ptrdiff_t delta = ((unsigned char *)to) - from;
	debug_dump("%p: ecall -> c.jalr %ld\t# %p\n", from, delta, to);
	const ptrdiff_t AUIPC_MAX_OFFSET = 2147479552;
	const ptrdiff_t AUIPC_MIN_OFFSET = -2147483648;
	if ((delta & 0xfff) != 0) {
		xabort("create_c_j misaligned instruction fetch exception");
	}
	if (delta >= AUIPC_MIN_OFFSET && delta <= AUIPC_MAX_OFFSET) {
		uint32_t auipc = 0x00000f97; // auipc t6, 0x.....
		uint16_t c_jr = 0x8f82; // c.jr t6
		uint32_t auipc_imm_field = (uint32_t)delta & 0xfffff000; // offset[31:12]
		auipc |= auipc_imm_field;
		*(uint32_t *)from = auipc;
		*(uint16_t *)(from + 4) = c_jr;
	} else {
		xabort("create_c_j distance check");
	}

}

/*
 * activate_patches()
 * Loop over all the patches, and overwrite each ecall.
 */
void
activate_patches(struct intercept_desc *desc)
{
	unsigned char *first_page;
	size_t size;

	if (desc->count == 0)
		return;

	first_page = round_down_address(desc->text_start);
	size = (size_t)(desc->text_end - first_page);

	mprotect_no_intercept(first_page, size,
	    PROT_READ | PROT_WRITE | PROT_EXEC,
	    "mprotect PROT_READ | PROT_WRITE | PROT_EXEC");

	for (unsigned i = 0; i < desc->count; ++i) {
		const struct patch_desc *patch = desc->items + i;
		debug_dump("\nactivating patch at dst_jmp_patch: 0x%lx - patch->return_address: 0x%lx - patch_n:%u\n"
			"patch_absolute_return_address: %p\n",
			patch->dst_jmp_patch-desc->base_addr,patch->return_address-desc->base_addr,i,patch->return_address);

		if (patch->dst_jmp_patch < desc->text_start ||
		    patch->dst_jmp_patch > desc->text_end)
			xabort("dst_jmp_patch outside text");

		/*
		 * The dst_jmp_patch pointer contains the address where
		 * the actual jump instruction escaping the patched text
		 * segment should be written.
		 * This is either at the place of the original syscall
		 * instruction, or at some usable padding space close to
		 * it (an overwritable NOP instruction).
		 */

		if (desc->uses_trampoline_table) {
			/*
			 * First jump to the trampoline table, which
			 * should be in a 2 gigabyte range. From there,
			 * jump to the asm_wrapper.
			 */
			check_trampoline_usage(desc);
			if (!patch->needs_compressed_ins) {

				/* jump - escape the text segment */
				create_j(patch->dst_jmp_patch, desc->next_trampoline);

				/*
				 * if patch is 10 bytes long, fill the last two
				 * with c.ebreak instruction. Template will jump back to the
				 * return address so c.ebreak will never be executed as long as
				 * the patching correctly writes the return jump from template.
				 */
				if (patch->padding_is_needed) {
					*(uint16_t *)(patch->return_address-2) = 0x8002; // c.ebreak
				}

				/* jump - escape the 2 GB range of the text segment */
				desc->next_trampoline = create_absolute_jump(
					desc->next_trampoline, patch->asm_wrapper);
			} else {
				const int rem = (desc->next_trampoline - patch->dst_jmp_patch) % 4096;
				if (rem) {
					desc->next_trampoline += 4096 - rem;
				}
				create_c_j(patch->dst_jmp_patch, desc->next_trampoline);

				desc->next_trampoline = create_absolute_jump(
					desc->next_trampoline, patch->asm_wrapper);
			}
		} else {
			create_j(patch->dst_jmp_patch, patch->asm_wrapper);
		}

	}

	mprotect_no_intercept(first_page, size,
	    PROT_READ | PROT_EXEC,
	    "mprotect PROT_READ | PROT_EXEC");
}
